# Generated by Django 5.2.17 on 2026-09-03 23:37

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('cashier', 'Cashier')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.restaurant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'username'), name='accounts_user_username_unique_per_restaurant', nulls_distinct=False), models.CheckConstraint(condition=models.Q(models.Q(('restaurant__isnull', True), ('role', 'super_admin')), models.Q(models.Q(('role', 'super_admin'), _negated=True), ('restaurant__isnull', False)), _connector='OR'), name='accounts_user_restaurant_null_only_for_super_admin')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
