# Generated by Django 5.2.17 on 2026-09-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=40, unique=True)),
                ('display_phone', models.CharField(blank=True, max_length=30)),
                ('access_token', models.CharField(max_length=512)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='tenants.restaurant')),
            ],
        ),
    ]
