# Generated by Django 5.2.17 on 2026-09-04 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='preparing', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.JSONField(default=list)),
                ('cashier', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'Qr')], max_length=10, null=True)),
                ('client_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CancellationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier', models.CharField(max_length=100)),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
