# Generated by Django 5.2.17 on 2026-09-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_conversationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='pending_proposal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
