# Generated by Django 5.2.17 on 2026-09-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifieroption',
            name='inventory_item_id',
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_options', to='inventory.inventoryitem'),
        ),
    ]
